import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import { useQuery } from 'react-query';
import axios from 'axios';
import styles from './home.module.css';
import Image from 'next/image';

const GET_YOUTUBE_VIDEO_LIST = '';

export default function Home() {
  const [popularVideoList, setPopularVideoList] = useState<any[]>([]);

  const getVideoList = useCallback(async () => {
    try {
      const res = await axios.get(`data/popular-video.json`);
      console.log(res);
      setPopularVideoList(res.data.items);
    } catch (e) {}
  }, []);

  const { data: videoList, isLoading, isError } = useQuery('popular-video', getVideoList);

  return (
    <>
      <Head>
        <title>youtube clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['video-list-wrap']}>
        {popularVideoList &&
          popularVideoList.map((video: any) => (
            <div key={video.id} className={styles.video}>
              <Image
                width={'100px'}
                height={'100px'}
                src={video.snippet.thumbnails.medium.url}
                alt=""
                className={styles['video-thumbnail']}
                layout="fixed"
              />
              <div className={styles['video-title']}>{video.snippet.title}</div>
              <div className={styles['video-channel']}>{video.snippet.channelTitle}</div>
              <div className={styles['video-upload-time']}>{video.snippet.publishedAt}</div>
            </div>
          ))}
      </div>
    </>
  );
}
