import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { useQuery } from "react-query";
import axios from "axios";
import styles from "./home.module.css";
import Image from "next/image";
import { useRouter } from "next/router";
import { getPopularVideoList } from "@/apis/youtube";
import AutoHeightImage from "@/components/autoHeightimage";

export default function Home() {
  const router = useRouter();
  const onClickVideo = useCallback(
    (videoId: string) => {
      router.push(`/videos/watch/${videoId}`);
    },
    [router]
  );
  const { data, isLoading, isError } = useQuery(
    "popular-video-list",
    getPopularVideoList
  );

  return (
    <div className={styles.home}>
      <Head>
        <title>youtube clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["video-list-wrap"]}>
        {data?.data.items.map((video: any) => (
          <div
            key={video.id}
            className={styles.video}
            onClick={() => onClickVideo(video.id)}
          >
            <AutoHeightImage imageUrl={video.snippet.thumbnails.medium.url} />
            <div className={styles["video-info"]}>
              <div className={styles["video-title"]}>{video.snippet.title}</div>
              <div>
                <div className={styles["video-channel"]}>
                  {video.snippet.channelTitle}
                </div>
                <div className={styles["video-upload-time"]}>
                  {video.snippet.publishedAt}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
