import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useCallback, useState } from 'react';
import { useQuery } from 'react-query';
import axios from 'axios';
import Head from 'next/head';
import styles from './search.module.css';
import Image from 'next/image';

const URL_SEARCHED_VIDEO_LIST = '';

const Serarch: NextPage = () => {
  const router = useRouter();
  const [searchedVideoList, setSearchedVideoList] = useState([]);
  const getSearchedVideoList = useCallback(async () => {
    try {
      const res = await axios.get(`/data/searched-video.json`);
      console.log(res);
      setSearchedVideoList(res.data.items);
    } catch (e) {}
  }, []);
  const { data, isLoading, isError } = useQuery('searched-video', getSearchedVideoList);

  return (
    <>
      <Head>
        <title>youtube clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['video-list-wrap']}>
        {searchedVideoList &&
          searchedVideoList.map((video: any) => (
            <div key={video.id} className={styles.video}>
              <Image
                width={'100px'}
                height={'100px'}
                src={video.snippet.thumbnails.medium.url}
                alt=""
                layout="fixed"
              />
              <div className={styles['video-title']}>{video.snippet.title}</div>
              <div className={styles['video-channel']}>{video.snippet.channelTitle}</div>
              <div className={styles['video-upload-time']}>{video.snippet.publishedAt}</div>
            </div>
          ))}
      </div>
    </>
  );
};

export default Serarch;
